//  Collect : Collect, Store and Forward industrial data
//  Copyright SPIA Tech India, www.spiatech.com
//  MIT License

export const GET_DASH_DEVICE_REQUEST = 'GET_DASH_DEVICE_REQUEST'
export const GET_DASH_DEVICE_REQUEST_SUCCESS = 'GET_DASH_DEVICE_REQUEST_SUCCESS'
export const GET_DASH_DEVICE_REQUEST_FAILED = 'GET_DASH_DEVICE_REQUEST_FAILED'

export const GET_DASH_GROUP_REQUEST = 'GET_DASH_GROUP_REQUEST'
export const GET_DASH_GROUP_REQUEST_SUCCESS = 'GET_DASH_GROUP_REQUEST_SUCCESS'
export const GET_DASH_GROUP_REQUEST_FAILED = 'GET_DASH_GROUP_REQUEST_FAILED'

export const GET_DASH_TAG_REQUEST = 'GET_DASH_TAG_REQUEST'
export const GET_DASH_TAG_REQUEST_SUCCESS = 'GET_DASH_TAG_REQUEST_SUCCESS'
export const GET_DASH_TAG_REQUEST_FAILED = 'GET_DASH_TAG_REQUEST_FAILED'

export const GET_DASH_ALERT_REQUEST = 'GET_DASH_ALERT_REQUEST'
export const GET_DASH_ALERT_REQUEST_SUCCESS = 'GET_DASH_ALERT_REQUEST_SUCCESS'
export const GET_DASH_ALERT_REQUEST_FAILED = 'GET_DASH_ALERT_REQUEST_FAILED'

export const GET_DASH_NOTIFICATION_REQUEST = 'GET_DASH_NOTIFICATION_REQUEST'
export const GET_DASH_NOTIFICATION_REQUEST_SUCCESS = 'GET_DASH_NOTIFICATION_REQUEST_SUCCESS'
export const GET_DASH_NOTIFICATION_REQUEST_FAILED = 'GET_DASH_NOTIFICATION_REQUEST_FAILED'
