//  Collect : Collect, Store and Forward industrial data
//  Copyright SPIA Tech India, www.spiatech.com
//  MIT License

// Fetch list of notification from the api
export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST'
export const GET_NOTIFICATION_REQUEST_SUCCESS = 'GET_NOTIFICATION_REQUEST_SUCCESS'
export const GET_NOTIFICATION_REQUEST_FAILED = 'GET_NOTIFICATION_REQUEST_FAILED'
export const GET_SELECTED_NOTIFICATION_REQUEST_SUCCESS = 'GET_SELECTED_NOTIFICATION_REQUEST_SUCCESS'

//Fetch list of alerts from api
export const GET_NOTIFICATION_ALERTS_REQUEST = 'GET_NOTIFICATION_ALERTS_REQUEST'
export const GET_NOTIFICATION_ALERTS_REQUEST_SUCCESS = 'GET_NOTIFICATION_ALERTS_REQUEST_SUCCESS'
export const GET_NOTIFICATION_ALERTS_REQUEST_FAILED = 'GET_NOTIFICATION_ALERTS_REQUEST_FAILED'
export const GET_NOTIFICATION_SELECTED_ALERTS_REQUEST_SUCCESS = 'GET_NOTIFICATION_SELECTED_ALERTS_REQUEST_SUCCESS'

// Fetch list of tags from the api
export const GET_NOTIFICATION_TAGS_REQUEST = 'GET_NOTIFICATION_TAGS_REQUEST'
export const GET_NOTIFICATION_TAGS_REQUEST_SUCCESS = 'GET_NOTIFICATION_TAGS_REQUEST_SUCCESS'
export const GET_NOTIFICATION_TAGS_REQUEST_FAILED = 'GET_NOTIFICATION_TAGS_REQUEST_FAILED'
export const REMOVE_NOTIFICATION_TAG_INFO = 'REMOVE_NOTIFICATION_TAG_INFO'


export const REMOVE_NOTIFICATION_INFO = 'REMOVE_NOTIFICATION_INFO'
export const FILTER_NOTIFICATION = 'FILTER_NOTIFICATION'
export const ISEDIT_NOTIFICATION = 'ISEDIT_NOTIFICATION'
export const SELECT_NOTIFICATION = 'SELECT_NOTIFICATION'
export const SELECT_NOTIFICATION_ALERT = 'SELECT_NOTIFICATION_ALERT'
export const SELECT_NOTIFICATION_ALERTID = 'SELECT_NOTIFICATION_ALERTID'
export const SELECT_NOTIFICATION_ALERTNAME = 'SELECT_NOTIFICATION_ALERTNAME'
export const SELECT_NOTIFICATION_TAG = 'SELECT_NOTIFICATION_TAG'
export const SELECT_NOTIFICATION_TAGNAME = 'SELECT_NOTIFICATION_TAGNAME'

export const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR'
export const REMOVE_SELECTED_ALERT = 'REMOVE_SELECTED_ALERT'
