//  Collect : Collect, Store and Forward industrial data
//  Copyright SPIA Tech India, www.spiatech.com
//  MIT License

// Fetch list of alerts from the api
export const SET_TAG_TYPE_ERROR = 'SET_TAG_TYPE_ERROR'
export const GET_TAG_TYPE_REQUEST = 'GET_TAG_TYPE_REQUEST'
export const GET_TAG_TYPE_REQUEST_SUCCESS = 'GET_TAG_TYPE_REQUEST_SUCCESS'
export const GET_TAGLIST_REQUEST = 'GET_TAGLIST_REQUEST'
export const GET_TAGLIST_REQUEST_SUCCESS = 'GET_TAGLIST_REQUEST_SUCCESS'

export const SELECT_TAGLIST_BY_ID = 'SELECT_TAGLIST_BY_ID'
export const SELECT_TAGLIST = 'SELECT_TAGLIST'
export const REMOVE_SELECTED_TAGLIST = 'REMOVE_SELECTED_TAGLIST'

export const SET_TAGLIST_ERROR = 'SET_TAGLIST_ERROR'
export const FILTER_TAGLIST = 'FILTER_TAGLIST'

export const GET_TAG_DEVICE_REQUEST = 'GET_TAG_DEVICE_REQUEST'
export const SET_TAG_DEVICE_ERROR = 'SET_TAG_DEVICE_ERROR'
export const SELECT_TAG_DEVICE_BY_ID = 'SELECT_TAG_DEVICE_BY_ID'
export const SELECT_TAG_DEVICE_NAME = 'SELECT_TAG_DEVICE_NAME'
export const SELECT_TAG_DEVICE_ID = 'SELECT_TAG_DEVICE_ID'
