//  Collect : Collect, Store and Forward industrial data
//  Copyright SPIA Tech India, www.spiatech.com
//  MIT License

// Fetch list of alerts from the api
export const SET_ALERTS_IMPORT_ERROR = 'SET_ALERTS_IMPORT_ERROR'
export const GET_IMPORT_REQUEST = 'GET_IMPORT_REQUEST'
export const GET_DELETING_ALL_DATAS = 'GET_DELETING_ALL_DATAS'
export const SET_IMPORT_SUCCESS = 'SET_IMPORT_SUCCESS'
export const SET_IMPORT_FAILED = 'SET_IMPORT_FAILED'
export const SET_IMPORT_NOTIFICATION_SUCCESS = 'SET_IMPORT_NOTIFICATION_SUCCESS'
export const GET_DELETING_ALERT_NOTIFICATION_DATAS = 'GET_DELETING_ALERT_NOTIFICATION_DATAS'
export const SET_IMPORT_NOTIFICATION_SUCCESS_FAILED = 'SET_IMPORT_NOTIFICATION_SUCCESS_FAILED'
export const GET_DELETING_ALERT_NOTIFICATION_DATAS_FAILED = 'GET_DELETING_ALERT_NOTIFICATION_DATAS_FAILED'
export const GET_DELETING_ALL_DATAS_FAILED = 'GET_DELETING_ALL_DATAS_FAILED'
