//  Collect : Collect, Store and Forward industrial data
//  Copyright SPIA Tech India, www.spiatech.com
//  MIT License

export const GET_EXPORT_ALERT_REQUEST = 'GET_EXPORT_ALERT_REQUEST'
export const GET_EXPORT_ALERT_REQUEST_SUCCESS = 'GET_EXPORT_ALERT_REQUEST_SUCCESS'
export const GET_EXPORT_ALERT_REQUEST_FAILED = 'GET_EXPORT_ALERT_REQUEST_FAILED'

export const GET_EXPORT_CONFIG_REQUEST = 'GET_EXPORT_CONFIG_REQUEST'
export const GET_EXPORT_CONFIG_REQUEST_SUCCESS = 'GET_EXPORT_CONFIG_REQUEST_SUCCESS'
export const GET_EXPORT_CONFIG_REQUEST_FAILED = 'GET_EXPORT_CONFIG_REQUEST_FAILED'
export const REMOVE_EXPORT_DATAS = 'REMOVE_EXPORT_DATAS'
